rotation = [
    "opener", 
    #"baseline x2", 
    "burst"
]

[custom.kazahana_phys_skip]
priority = 1
values = [
    "kazahana 3",
    "kazahana 4",
    "kazahana 5"
]

[custom.kazahana_full]
priority = 1
values = [
    "kazahana 1",
    "kazahana 2",
    "kazahana 3",
    "kazahana 4",
    "kazahana 5"
]

[custom.hisetsu_full]
priority = 1
values = [
    "hisetsu 1",
    "hisetsu 2"
]

[custom.opener]
priority = 2
values = [
    "hisetsu 1",
    "kazahana_phys_skip",
    "shimotsuki 3"
]

[custom.baseline]
priority = 2
values = [
    "kazahana_full x4",
    "hisetsu_full",
    "kazahana_phys_skip",
    "kazahana_full x3",
    "hisetsu 1",
    "frostburn",
    "shimotsuki 3",
    "shatter"
]

[custom.burst]
priority = 2
values = [
    "lingering_snow 1",
    "frostburn",
    "shimotsuki 3",
    "shatter"
]