GET http://127.0.0.1:5102 HTTP/1.1

###
POST http://127.0.0.1:5102/damage?type=detailed HTTP/1.1
Content-Type: application/json

{
    "aid": 1091,
    "wid": 14109,
    "discs": [
        {
            "id": 32500,
            "rarity": 4,
            "stats": ["HpFlat", "DefPenFlat", "Ap", "CritDmg", "CritRate"],
            "levels": [15, 0, 2, 2, 1]
        },
        {
            "id": 32800,
            "rarity": 4,
            "stats": ["AtkFlat", "Ap", "AtkRatio", "CritDmg", "CritRate"],
            "levels": [15, 2, 0, 2, 1]
        },
        {
            "id": 32500,
            "rarity": 4,
            "stats": ["DefFlat", "AtkFlat", "CritRate", "CritDmg", "HpFlat"],
            "levels": [15, 0, 2, 2, 0]
        },
        {
            "id": 32800,
            "rarity": 4,
            "stats": ["CritDmg", "HpFlat", "HpRatio", "CritRate", "DefPenFlat"],
            "levels": [15, 1, 1, 3, 0]
        },
        {
            "id": 32800,
            "rarity": 4,
            "stats": ["IceRatio", "CritDmg", "CritRate", "DefFlat", "HpRatio"],
            "levels": [15, 1, 1, 0, 2]
        },
        {
            "id": 32800,
            "rarity": 4,
            "stats": ["AtkRatio", "HpFlat", "CritDmg", "AtkFlat", "CritRate"],
            "levels": [15, 1, 1, 2, 0]
        }
    ],
    "rotation": 1
}

###
PUT http://127.0.0.1:5102/rotation?aid=1261&id=0 HTTP/1.1
Content-Type: application/json

{
    "rotation": [
        "flowers_of_sin",
        "phantom_thrust",
        "salchow_jump 1",
        "assault",
        "salchow_jump 2",
        "aerial_sweep_cleanout",
        "aerial_sweep_cleanout",
        "assault",
        "phantom_thrust",
        "final_curtain",
        "assault"
    ]
}